### ISSUE TITLE
Incorrect cycle completion percent

### ISSUE THREAD

**Issue by damirishpreet** [Chuckv01/wendler-log-public#88]
Hi, When I remove Delgado week from cycle the completion percentages for the cycle are off. I completed 3 weeks in a 3 week cycle but total cycle completion percent is showing 43%

**Comment by Chuckv01** [comment]
Try setting the number of weeks in the cycle to 3 as well. That should fix the issue...

**Comment by damirishpreet** [comment]
Hi Chuck,

I did that, please see the screenshots.

Regards,
Ishpreet S Damir.
+19736410149

Try setting the number of weeks in the cycle to 3 as well. That should fix
the issue...
