### ISSUE TITLE
Ability to base new cycles off of log's 1rep maxes

### ISSUE THREAD

**Issue by rob-mcgrail** [Chuckv01/wendler-log-public#90]
Currently new cycles calculate off of your original 1rms. It would be cool to be able to leapfrog, setting new cycles to scale off of the most recent 1 rep maxes from your log instead.

**Comment by Chuckv01** [comment]
Hmm, feel free to correct me if I am wrong:

But isn't the spirit of wendler is to get stronger slowly over time in a controlled manner? This feature would cause someone to jump up in weight, which would defeat the purpose of slowly building strength.

You can always go into the cycle options and adjust the cycle 1RMs higher if you want to jump up in weight based off your calculated 1RMs in your last cycle.

**Comment by robomc** [comment]
It's definitely not in the spirit of wendler, but one of the key cool things about your app IMO is how it lets you create your own vaguely-wendler-inspired program.

An example of where it would be cool, is where you get yourself into a situation where a new PR is going to require some ridiculously high number of reps - say, 10, on week 2. Would be nice occasionally to be able to say "I'm killing it at the moment, let's just start a new cycle based on my current strength, as if I was starting the program brand new.

Unlikely to happen to anyone but novices/intermediates, but it would have its uses for those people I think.

Anyway just putting it forward in case it's something other people think would be useful - appreciate you reading these, and the level of customisation you offer already.

**Comment by rob-mcgrail** [comment]
Fair enough - it can be achieved manually via the cycle options. 

Would still be a cool convenience feature IMO (although not in the spirit of wendler, the ability to create weird wendler-inspired variants is one of the cool aspects of your app) but I'll close since it's relatively straightforward to achieve as is.

**Comment by Chuckv01** [comment]
Thanks for closing :+1:
