### ISSUE TITLE
Incorporate Beyond 5-3-1 Methods

### ISSUE THREAD

**Issue by rcoundon** [Chuckv01/wendler-log-public#91]
Wendler added a lot of detail in Beyond 5-3-1, it would be really good to have these as options in the app.
E.g. Joker Sets, First Set Last, multiple cycles before deload.

**Comment by Chuckv01** [comment]
Good thoughts. Some of these features are in the app now.

Joker Sets are available in the pro version, as well as adjusting the number of cycles before a deload week (or disabling the deload weeks completely). 

The other features I hope to get into an upcoming update.

**Comment by rcoundon** [comment]
Thanks - I've got the Pro version, hadn't noticed Joker Sets under assistance for some reason.
Re: cycles before deload - If I change number of weeks in cycle to 6, I'm told by the app that I need to add a brand new cycle so that it can be recalculated.  I assume I should therefore wait until I have finished the current cycle, delete the fresh one that's created and then adjust the number of weeks?

**Comment by Chuckv01** [comment]
No, after you adjust the number of week settings you should only need to create one new cycle, and won't need to delete anything.

The reason is the cycle settings don't take effect till you create your next cycle. They won't modify your current or past cycles.

Hope that makes sense?

**Comment by rcoundon** [comment]
Makes perfect sense, thanks for coming back to me
